# Generated by Django 3.2.23 on 2023-12-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20231219_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='friendly_name',
            new_name='display_name',
        ),
    ]
